// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mndloubobaeubrctiwpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZGxvdWJvYmFldWJyY3Rpd3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTU2NzMsImV4cCI6MjA2ODA5MTY3M30.AtdAu1MOzDfdc9GphRN5Vwat8WqHlUrv6-rNGhTgxRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});